export const icons = {
  javascript: 'simple-icons:javascript',
  typescript: 'simple-icons:typescript',
  vuejs: 'simple-icons:vuedotjs',
  nuxtjs: 'simple-icons:nuxtdotjs',
  nodejs: 'simple-icons:nodedotjs',
  php: 'simple-icons:php',
  laravel: 'simple-icons:laravel',
  mysql: 'simple-icons:mysql',
  postgresql: 'simple-icons:postgresql',
  mongodb: 'simple-icons:mongodb',
  docker: 'simple-icons:docker',
  kubernetes: 'simple-icons:kubernetes',
  aws: 'simple-icons:amazonaws',
  googlecloud: 'simple-icons:googlecloud',
  cicd: 'simple-icons:githubactions',
  terraform: 'simple-icons:terraform',
  ansible: 'simple-icons:ansible',
  linux: 'simple-icons:linux',
  crypto: 'simple-icons:bitcoin',
  wordpress: 'simple-icons:wordpress',
  network: 'simple-icons:serverless',
  database: 'simple-icons:serverless',
};
